### ISSUE TITLE
Create model: Study Group

### ISSUE THREAD

**Issue by ghost** [DelegacionUC3M/estudio#3]
Implementar modelo de Grupo de Estudio.

- [x] Clase objeto
- [x] Constructor: función __init__
- [x] Print: función __repr__

[Link a la wiki](https://delegacion.uc3m.es/wiki/doku.php?id=comision_tic:apps:sgrudadh:inicio)

**Comment by SantiEspada** [comment]
Mmm creo que he hecho un commit tal cual en vez de un pull request xD pero bueno, si hay que cambiar algo del modelo decídnoslo xD
